version: '3.8'
services:
  web:
    image: nginx:1.21.5-alpine
    container_name: nginx-container
    ports:
      - ${HTTP_PORT}:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ${PROJECT_DIR}:${WORDK_DIR}
    networks:
      - app-net
    depends_on:
      - php

  php:
    image: php:7.4-fpm
    container_name: php-container
    volumes:
      - ${PROJECT_DIR}:${WORDK_DIR}
    expose:
      - 9000
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
